stages:
  - prepare
  - build

before_build:
  stage: prepare
  script:
    - $MAVEN_HOME/bin/mvn clean

maven-build:
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
