image:
  name: terraform:latest

before_script:
  - export AWS_ACCESS_KEY_TF='${AWS_ACCESS_KEY}'"
  - export AWS_SECRET_KEY_TF='${AWS_SECRET_KEY}'"

stages:
  - fmt
  - validate
  - plan
  - apply


fmt:
  stage: fmt
  script:
    - terraform fmt -recursive -check=true -diff=true
  
